# 1.Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np
def add(mat1,mat2):
    return mat1+mat2
r1=int(input('Enter the no of rows of 1st Matrix:'))
c1=int(input('Enter the no of columns of 1st Matrix:'))
elements1=list(map(int,input('Enter the elements for 1st matrix:').split()))
mat1=np.array(elements1).reshape(r1,c1)
print('1st matrix:',end='\n')
print(mat1)

r2=int(input('Enter the no of rows of 2nd Matrix:'))
c2=int(input('Enter the no of columns of 2nd Matrix:'))
elements2=list(map(int,input('Enter the elements for 2nd matrix:').split()))
mat2=np.array(elements2).reshape(r2,c2)
print('2nd matrix:',end='\n')
print(mat2)

sum=add(mat1,mat2)
print('Sum of matrices:',end='\n')
print(sum)
    

Enter the no of rows of 1st Matrix:2
Enter the no of columns of 1st Matrix:2
Enter the elements for 1st matrix:10 10 10 10
1st matrix:
[[10 10]
 [10 10]]
Enter the no of rows of 2nd Matrix:2
Enter the no of columns of 2nd Matrix:2
Enter the elements for 2nd matrix:10 10 10 10
2nd matrix:
[[10 10]
 [10 10]]
Sum of matrices:
[[20 20]
 [20 20]]


# 2.Write a Python Program to Multiply Two Matrices?

In [9]:
import numpy as np
def multiply(mat1,mat2):
    return np.dot(mat1,mat2)
r1=int(input('Enter the no of rows of 1st Matrix:'))
c1=int(input('Enter the no of columns of 1st Matrix:'))
elements1=list(map(int,input('Enter the elements for 1st matrix:').split()))
mat1=np.array(elements1).reshape(r1,c1)
print('1st matrix:',end='\n')
print(mat1)

r2=int(input('Enter the no of rows of 2nd Matrix:'))
c2=int(input('Enter the no of columns of 2nd Matrix:'))
elements2=list(map(int,input('Enter the elements for 2nd matrix:').split()))
mat2=np.array(elements2).reshape(r2,c2)
print('2nd matrix:',end='\n')
print(mat2)

prod=multiply(mat1,mat2)
print('Multiplication of matrices:',end='\n')
print(prod)

Enter the no of rows of 1st Matrix:2
Enter the no of columns of 1st Matrix:2
Enter the elements for 1st matrix:3 3 3 3
1st matrix:
[[3 3]
 [3 3]]
Enter the no of rows of 2nd Matrix:2
Enter the no of columns of 2nd Matrix:2
Enter the elements for 2nd matrix:4 4 4 4
2nd matrix:
[[4 4]
 [4 4]]
Multiplication of matrices:
[[24 24]
 [24 24]]


# 3.Write a Python Program to Transpose a Matrix?

In [13]:
import numpy as np
def transpose(mat):
    print('Transpose of a Matrix:',end='\n')
    print(mat.T)
r=int(input('Enter the no of rows of Matrix:'))
c=int(input('Enter the no of columns of Matrix:'))
elements=list(map(int,input('Enter the elements for matrix:').split()))
mat=np.array(elements).reshape(r,c)
print('Entered matrix:',end='\n')
print(mat)

transpose(mat)
    

Enter the no of rows of Matrix:3
Enter the no of columns of Matrix:3
Enter the elements for matrix:1 2 3 4 5 6 7 8 9
Entered matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of a Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 4.Write a Python Program to Sort Words in Alphabetic Order?

In [6]:
def alphabetical_sort(sent1):
    sent2=sent1.split()
    sent3=sorted(sent2)
    print(sent3)
    
sent1=input('Enter a Sentence:')
alphabetical_sort(sent1)

    

Enter a Sentence:i am pabitra kumar pradhan
['am', 'i', 'kumar', 'pabitra', 'pradhan']


# 5.Write a Python Program to Remove Punctuation From a String?

In [13]:
def remove_punctuation(str1):
    punctuations='!()-[]{};:\'"\,<>./?@#$%^&*_~'
    str2=''
    for i in str1:
        if i not in punctuations:
            str2+=i
    print('String without punctuations',str2)
    
str1=input('Enter a String')
remove_punctuation(str1)

Enter a Stringm*
String without punctuations m
